apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-service
  namespace: demo-devops
  labels:
    app: tasks-service
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: tasks-service
  template:
    metadata:
      labels:
        app: tasks-service
    spec:
      containers:
      - name: tasks-service
        image: tasks-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: tasks-config
        - secretRef:
            name: tasks-secrets
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: tasks-config
              key: PORT
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: tasks-config
              key: NODE_ENV
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: tasks-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: tasks-config
              key: DB_PORT
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: tasks-config
              key: DB_USER
        # Password depuis Secret
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tasks-secrets
              key: DB_PASSWORD
        # Construire DATABASE_URL à partir des variables
        - name: DATABASE_URL
          value: "postgres://$(DB_USER):$(DB_PASSWORD)@$(DB_HOST):$(DB_PORT)/taskdb"